Initial Games Bet endpoint
richardaspinall/poker-react-node pull request #159
Opened 2024-06-26 23:28 UTC by tommy-trombone

### Description

This endpoint is for making a bet

### How to test

Just endpoint scaffolding/skeleton at the moment

### Task

[CU-86cvbdgx6](https://app.clickup.com/t/86cvbdgx6)

2024-06-26 23:28 UTC, richardaspinall commented
Task linked: [CU-86cvbdgx6 [BE] generate actions endpoints](https://app.clickup.com/t/86cvbdgx6)

2024-06-27 00:57 UTC, richardaspinall requested changes
Looks good. One minor thing!

2024-06-27 00:57 UTC, richardaspinall commented on backend/src/shared/api/metadata/games_bet.json
> +          "name": "betAmount",
could we just have this as `amount`?

2024-06-27 01:31 UTC, tommy-trombone commented on backend/src/shared/api/metadata/games_bet.json
> +          "name": "betAmount",
Yup!

2024-07-02 22:45 UTC, richardaspinall approved these changes

2024-07-02 22:49 UTC, merged